version: '3'
services:
  database:
    image: "postgres:latest" # use latest official postgres version
    container_name: postgres_container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_database
    #env_file:
    # - database.env # configure postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  database-data: # named volumes can be managed easier using docker-compose
